[package]
name = "server"
version = "0.0.0"
authors = ["Martin Zl√°mal <mrtnzlml@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arangodb = { path = "../arangodb" }
auth = { path = "../auth" }
env_logger = "0.8.2"
juniper = { git = "https://github.com/graphql-rust/juniper" }
juniper_warp = { git = "https://github.com/graphql-rust/juniper" }
log = "0.4.0"
sdui = { path = "../sdui" }
tokio = { version = "0.2", features = ["rt-core", "macros"] }
warp = "0.2.5"

[dev-dependencies]
proptest = "0.10.1"
